Created ActivityStream page and its related classes
AaronQA/B36_GR4-CRM_Sprint-2 pull request #4
Opened 2024-10-30 08:11 UTC by StepanRiazhkin

Many things have been done!
Yet many things await to be done!

2024-10-30 14:31 UTC, AaronQA requested changes
I am sending a message about it
please make changes accordingly

2024-10-31 07:15 UTC, StepanRiazhkin commented on src/test/java/com/crm/pages/LoginPage.java
Here I deleted unused imports (amount of 3)

2024-10-31 07:15 UTC, StepanRiazhkin commented on src/test/java/com/crm/runners/CukesRunner.java
Just deleted excessive spaces

2024-10-31 07:17 UTC, StepanRiazhkin commented on src/test/java/com/crm/step_definitions/LoginPageStepDefs.java
Deleted my makeshift method for Logging in, now I use Mahrukh's method

2024-10-31 07:17 UTC, StepanRiazhkin commented on src/test/resources/features/US_12_Appreciation.feature
Tested with all the data here and commented out some spares login data

2024-10-31 07:22 UTC, StepanRiazhkin commented on src/test/java/com/crm/pages/ActivityStreamPage.java
> +
The method I've created below "clicksAndCheckIfNoDisplayed" to process my two tests, where I should be adding uploaded files into the text, and where I should be deleting all the elements. In such way I had to decrease the implicit wait duration for a while, in order to do not wait for the element that has been already deleted. And after I've set the implicit duration back. And I had to "catch" the NoSuchElementException as there're no such elements after they have been removed in the while loop.

2024-10-31 14:48 UTC, AaronQA requested changes
can you change the login you used. I am sending a message about it

2024-10-31 17:27 UTC, StepanRiazhkin commented
> can you change the login you used. I am sending a message about it

Fixed!

2024-10-31 19:02 UTC, AaronQA approved these changes

2024-10-31 19:02 UTC, merged